apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muchtodo-ingress
  namespace: muchtodo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: muchtodo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: muchtodo-backend
            port:
              number: 80
