apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: muchtodo
spec:
  type: NodePort
  selector:
    app: muchtodo-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
